#:schema node_modules/wrangler/config-schema.json
name = "sublink4030"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "431399f87ac440899a339aa08b3b4141" }
]

[assets]
directory = "./public"
